# Generated by Django 4.0.7 on 2022-08-26 16:53

import apps.core.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('text', apps.core.blocks.TextBlock()), ('alert', wagtail.blocks.StructBlock([('alert_type', wagtail.blocks.ChoiceBlock(choices=[('Warning', 'Warning'), ('Note', 'Note')])), ('alert_body', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link']))]))], use_json_field=True),
        ),
    ]
