# Generated by Django 4.0.6 on 2022-07-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='table_of_contents',
            field=models.TextField(blank=True),
        ),
    ]
