# Generated by Django 4.0.6 on 2022-09-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contentpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='table_of_contents',
            field=models.TextField(blank=True),
        ),
    ]
