# Generated by Django 4.0.7 on 2022-09-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback items'},
        ),
    ]
