# Generated by Django 4.1.2 on 2022-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_initial_footercontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="introduction",
            field=models.TextField(blank=True),
        ),
    ]
