# Generated by Django 4.2.7 on 2025-11-20 18:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_default_homepage_introduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="introduction",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
