# Generated by Django 4.1.2 on 2022-11-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_default_homepage_introduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionPage",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.contentpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.contentpage",),
        ),
    ]
