# Generated by Django 6.0.6 on 2026-07-09 05:39

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_footercontent_locale_alter_footeritem_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('text_annotated', 4), ('alert', 7)], block_lookup={0: ('apps.core.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Wagtail version, in x.y format, e.g. 7.4 or 8.10.', 'max_length': 20, 'required': False, 'validators': [django.core.validators.RegexValidator(message='Enter a version in x.y format, e.g. 7.4 or 8.10.', regex='^\\d+\\.\\d+$')]}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('added', 'Added'), ('changed', 'Changed'), ('removed', 'Removed')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('content', 1), ('version', 2), ('change_type', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Warning', 'Warning'), ('Note', 'Note')]}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 7: ('wagtail.blocks.StructBlock', [[('alert_type', 5), ('alert_body', 6)]], {})}),
        ),
    ]
