# Generated by Django 5.2.9 on 2026-01-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_footercontent_locale_alter_footeritem_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='table_of_contents',
        ),
    ]
