# Generated by Django 6.0.6 on 2026-08-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contentpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='table_of_contents',
        ),
    ]
