# Generated by Django 4.0.6 on 2022-07-14 15:34

import apps.home.blocks
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=wagtail.fields.StreamField([('section_grid', apps.home.blocks.SectionGridBlock())], null=True, use_json_field=True),
        ),
    ]
